print ("Content-type:text/html")
print ()                              # 空行，告诉服务器结束头部
print ('<html>')
print ('<head>')
print ('<meta charset="utf-8">')
print ('<title>Hello Word - 我的第一个 CGI 程序！</title>')
print ('</head>')
print ('<body>')
print ('<h2>兔园标物序，惊时最是梅。衔霜当路发，映雪拟寒开。</h2>')
print ('</body>')
print ('</html>')
